### PR TITLE
Refactor to create v2

### PR DESCRIPTION
**Pull request by djoyner**
* Service is now a `struct` instead of an `interface`.

* Switched to `httptreemux`, which allows for more flexible request routing.

* Resource abstraction improvements:

  * Eliminated the `Resource` interface in terms of fine-grained interfaces like
    `CollectionLister` and `SingletonUpdater`. This allows the service to
    perform runtime type assertions during resource registration and in turn it
    can automatically create routes based on what the resource actually
    supports.

  * The service creates a router instance per API version. When resources are
    registered, they are explicitly registered in one of these instances. This
    allows for complete per-version separation at the type level and makes
    request handling much cleaner for multi-versioned services.

* Request processing improvements:

  * Allocate ResponseWriter and handlerDetails from `sync.Pool`.

  * Middleware handlers are now typed as `http.Handler`. Many unnecessary and
    confusing types have been removed.

  * Middleware dispatch now avoids recursion and deep call stacks.

* Logging improvements:

  * If the both the service logger and access logger are logging to stdout, then
    share the same logger instance to avoid mixing outputs.

  * Request latencies are now logged in seconds instead of milliseconds (which
    was confusing since we tend to log in seconds everywhere else).

* Removed the `vendor` directory.

* Updated the `README`.

---
This change is [Reviewable](https://reviewable.io/reviews/spirentorion/luddite.v2/1)

### CODE REVIEW

**Comment by VasuSankaran** [comment]
Review status: 0 of 384 files reviewed at latest revision, 1 unresolved discussion.

---

*[response_writer.go, line 30 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5EfGvZTUfdm1WzPuKM:-L5EfGvZTUfdm1WzPuKN:bqhod32) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/response_writer.go#L30)):*
> ```Go
> // NB: New fields added to this structure must be explicitly initialized in the
> // init method below. This enables pool-based allocation.
> type responseWriter struct {
> ```

Why should this object be pooled? After all the base http.ResonseWriter, which presumably is the meat, is allocated elsewhere and is simply being referenced from this struct. Aside from that all we have is a couple of int fields.
Not that I am against pooling but this seems to be the least offender.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1)*

**Comment by djoyner** [comment]
Review status: 0 of 384 files reviewed at latest revision, 1 unresolved discussion.

---

*[response_writer.go, line 30 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5EfGvZTUfdm1WzPuKM:-L5EhzzTMYYGHn5kD-y9:bq5u4v9) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/response_writer.go#L30)):*
<details><summary><i>Previously, VasuSankaran wrote…</i></summary><blockquote>

Why should this object be pooled? After all the base http.ResonseWriter, which presumably is the meat, is allocated elsewhere and is simply being referenced from this struct. Aside from that all we have is a couple of int fields.
Not that I am against pooling but this seems to be the least offender.
</blockquote></details>

You are correct that some type that implements the `http.ResponseWriter` interface is being allocated by the `net/http` package. It is unfortunate that we have to wrap that, but we do. And wrapping it means that we have to allocate our own `responseWriter`. There is going to be one of these allocations per request. So, it's not so much the size of the struct (which is small at 24 bytes), it's the frequency of allocation. I switched to pool-based allocation for both structs that we have to allocate on a per-request basis: this one and `handlerDetails`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1)*

**Comment by VasuSankaran** [comment]
:lgtm:

---

Review status: 0 of 384 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-:-L5EjLzvLZmIqmgN4Kua:bnfp4nl)*

**Comment by mourad** [comment]
Review status: 0 of 384 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5Fn4GTrZ60KTFoajDU:-L5Fn4GTrZ60KTFoajDV:b-9afavj) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/README.md#L9)):*
> ```Markdown
> 
> [golang]: http://golang.org/
> [apistds]: https://github.com/SpirentOrion/orion-api/blob/master/doc/api/api-standards.md
> ```

since luddite is a public repo, should we consider not linking to a private repo?

---

*[resource.go, line 165 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5Fu5p2uCL6PEzyWJm3:-L5Fu5p2uCL6PEzyWJm4:b-kmi4px) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/resource.go#L165)):*
> ```Go
> 		}
> 	})
> 	router.DELETE(basePath, func(rw http.ResponseWriter, req *http.Request) {
> ```

it doesn't seem like there's anyway to disable collection deletion anymore. Is the intent to have the resource handler determine that when `id == ""`?

---

*[response_writer.go, line 58 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5G0UosEID1XqIcuTod:-L5G0UosEID1XqIcuToe:b-8x3a76) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/response_writer.go#L58)):*
> ```Go
> 
> func (rw *responseWriter) Written() bool {
> 	return rw.status != 0
> ```

I realize this is just a refactor, but do you have any concern about a race condition? I guess not but figured I'd ask.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1)*

**Comment by djoyner** [comment]
Review status: 0 of 384 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5Fn4GTrZ60KTFoajDU:-L5GeqBffE5TKUZ2zWj_:b5hs4r7) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/README.md#L9)):*
<details><summary><i>Previously, mourad (Danilo Moura) wrote…</i></summary><blockquote>

since luddite is a public repo, should we consider not linking to a private repo?
</blockquote></details>

This link was pre-existing. The reason for `luddite` to be public has more to do with `orion-client`. I'm not terribly worried about a dead private link.

---

*[resource.go, line 165 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5Fu5p2uCL6PEzyWJm3:-L5Gez6XtRgmNY2tDb5c:bv8gy1f) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/resource.go#L165)):*
<details><summary><i>Previously, mourad (Danilo Moura) wrote…</i></summary><blockquote>

it doesn't seem like there's anyway to disable collection deletion anymore. Is the intent to have the resource handler determine that when `id == ""`?
</blockquote></details>

Luddite v1 automatically registered both routes for collection-style resources, so this isn't really a change. Resource handlers that don't want to implement this will see an unknown `id` as a no-op (since they return `204` on unknown ids).

---

*[response_writer.go, line 58 at r1](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1#-L5G0UosEID1XqIcuTod:-L5GfCaFtRfwy7mAFul6:b-hs8vha) ([raw file](https://github.com/spirentorion/luddite.v2/blob/32eda3162046322734368efcfdea6d2ed8fa5ef7/response_writer.go#L58)):*
<details><summary><i>Previously, mourad (Danilo Moura) wrote…</i></summary><blockquote>

I realize this is just a refactor, but do you have any concern about a race condition? I guess not but figured I'd ask.
</blockquote></details>

Hmm, never even considered it. This wrapper really just exists for `luddite` itself. Originally so the `bottom` handler could log/trace info about the response. And now to assist with middleware dispatch. I'm not too worried about race conditions as I don't think there would be an expectation that these methods are safe for concurrent use.

But that said, I'm now thinking of not exposing `luddite.ResponseWriter` at all. The wrapper would still exist but would be exposed as the `http.ResponseWriter` interface. I'll look into that tomorrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite.v2/1)*

**Pull request merged**
